CREATE TABLE 'Metals' (
    'id' INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    'metal' NVARCHAR(160) NOT NULL,
    'price' NUMERIC(5,2) NOT NULL
);

CREATE TABLE 'Sizes' (
    'id' INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    'carets' NUMERIC(5,2),
    'price' NUMERIC(5,2) NOT NULL
);

CREATE TABLE 'Styles' (
    'id' INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    'style' NVARCHAR(160) NOT NULL,
    'price' NUMERIC(5,2) NOT NULL
);

CREATE TABLE 'Orders' (
    'id' INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    'metal_id' INTEGER NOT NULL,
    'size_id' INTEGER NOT NULL,
    'style_id' INTEGER NOT NULL,
    FOREIGN KEY ('metal_id')
);

